spring:
  datasource:
    url: jdbc:mysql://ec2-13-113-245-111.ap-northeast-1.compute.amazonaws.com/securities_master
    username: root
    password: OC1013122
    driver-class-name: com.mysql.jdbc.Driver

logging:
  path: f:\DefaultLogDirectory\securities
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE
