spring:
  datasource:
    url: jdbc:mysql://localhost/securities_master
    username: ******
    password: ******
    driver-class-name: com.mysql.jdbc.Driver

logging:
  path: log
  level:
    root: WARN
    org:
      springframework:
        security: WARN
      hibernate:
        SQL: WARN
        type.descriptor.sql.BasicBinder: WARN
